import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';
import {layout as L,move} from './layout.js';
import {materials} from './materials.js';
import {architecture} from './scene.js';
import {furniture} from './furniture.js';
import {environment} from './environment.js';
import {details} from './details.js';
import {sky} from './sky.js';
import {chiselAssets} from './chisel-assets.js';
import {interfaceUI} from './interface.js';
import {mapSurfaces} from './surface-mapping.js';
import {optimize} from './optimize.js';
import embedded from 'embedded:assets';
async function start(){
const canvas=document.getElementById('viewport'),renderer=new T.WebGLRenderer({canvas,antialias:true,preserveDrawingBuffer:true});const gl=renderer.getContext(),debug=gl.getExtension('WEBGL_debug_renderer_info'),software=debug?/swiftshader|llvmpipe/i.test(gl.getParameter(debug.UNMASKED_RENDERER_WEBGL)):false;renderer.setPixelRatio(software?.6:Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.autoUpdate=false;renderer.shadowMap.needsUpdate=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.0;renderer.outputColorSpace=T.SRGBColorSpace;
const scene=new T.Scene(),model=new T.Group();model.name='AZIMUT SPBS REV05 — reconstrução interpretativa';scene.add(model);const m=materials(),arch=architecture(model,m),furn=furniture(model,m),garden=environment(model,m),decor=details(model,m),aux=await chiselAssets(model,m,embedded.glb);aux.set('glb');mapSurfaces(model);for(const g of [arch.lower,arch.upper,arch.boats,furn.lower,furn.upper,garden,decor])optimize(g);
const atmosphere=sky(scene,renderer);const hemi=new T.HemisphereLight('#e0efff','#a28b6b',2.4);scene.add(hemi);const sun=new T.DirectionalLight('#fff4df',3.5);sun.position.set(-10,30,25);sun.castShadow=true;sun.shadow.mapSize.set(software?1024:2048,software?512:2048);Object.assign(sun.shadow.camera,{left:-32,right:32,top:32,bottom:-32,near:1,far:100});sun.shadow.bias=-.0004;sun.shadow.normalBias=.04;sun.target.position.set(16,0,11);scene.add(sun,sun.target);
for(const p of [[17,2.15,3],[18,2.15,12],[10,2.15,9],[15,5.7,10],[22,5.7,10],[15,5.7,17],[22,5.7,17]]){const l=new T.PointLight('#ffdbab',p[1]>4?12:16,16,2);l.position.set(...p);scene.add(l);}
const ground=new T.Mesh(new T.PlaneGeometry(500,500),new T.MeshStandardMaterial({color:'#10120f',roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.29;ground.receiveShadow=true;scene.add(ground);
const camera=new T.PerspectiveCamera(43,1,.05,600),orbit=new OrbitControls(camera,canvas);orbit.enableDamping=!software;orbit.dampingFactor=.085;orbit.minDistance=.3;orbit.maxDistance=240;orbit.maxPolarAngle=Math.PI*.49;orbit.target.set(15,1.4,11);
let dirty=true;orbit.addEventListener('change',()=>dirty=true);let walking=false,currentView='overall',yaw=0,pitch=0,feet=[3.5,0,20],cut=false,ui;const keys=new Set();
const setLook=target=>{const dir=new T.Vector3(...target).sub(camera.position).normalize();yaw=Math.atan2(-dir.x,-dir.z);pitch=Math.asin(dir.y);camera.rotation.order='YXZ';camera.rotation.set(pitch,yaw,0);};
function home(){dirty=true;camera.near=.05;camera.fov=43;camera.updateProjectionMatrix();ui?.status(cut?'Corte de leitura · pavimento superior oculto':'Projeto REV05 · cotas documentadas + geometria estimada');walking=false;orbit.enabled=true;ui?.walk(false);currentView='overall';const f=Math.max(1,1.12/(innerWidth/innerHeight));camera.position.set(15-39*f,1.3+25.7*f,11+31*f);orbit.target.set(15,1.3,11);orbit.update();}
function view(id){dirty=true;if(id==='overall'){home();return;}currentView=id;camera.near=id==='top'?1:.05;camera.fov=id==='top'?2*Math.atan(Math.max(29,36/(innerWidth/innerHeight))/360)*180/Math.PI:43;camera.updateProjectionMatrix();const z=id==='top'?{name:'Vista aérea · comparação com a planta',level:2.7,eye:[16,180,11.501],target:[16,0,11.5]}:id==='materials'?{name:'Materiais · vista do render',level:2.7,eye:[10.5,8,22],target:[19,2.7,10]}:L.zones.find(z=>z.id===id);walking=false;orbit.enabled=true;ui.walk(false);camera.position.set(...z.eye);orbit.target.set(...z.target);orbit.update();ui.status(`${z.name} · ${z.level===0?'Lower Deck':'Main Deck'} · posição estimada`);}
function mode(){dirty=true;camera.near=.05;camera.fov=43;camera.updateProjectionMatrix();walking=!walking;orbit.enabled=!walking;keys.clear();ui.walk(walking);if(walking){const z=L.zones.find(z=>z.id===currentView)||L.zones[0];feet=[z.eye[0],z.level,z.eye[2]];camera.position.set(...z.eye);setLook(z.target);canvas.focus();}else{const dir=new T.Vector3();camera.getWorldDirection(dir);orbit.target.copy(camera.position).addScaledVector(dir,4);orbit.update();}}
function light(v){dirty=true;renderer.shadowMap.needsUpdate=true;atmosphere.set(v);const render=v==='render',evening=v==='evening';sun.color.set(render?'#ffe4bd':evening?'#ffd3a0':'#fff4e4');sun.intensity=render?1.65:evening?2:2.7;sun.position.set(...(evening?[-25,12,18]:[-10,30,25]));hemi.color.set(render?'#ece2cf':'#e0efff');hemi.intensity=render?.4:evening?.85:1.6;ground.material.color.set(render?'#10120f':evening?'#30332d':'#777e75');document.body.dataset.light=v;ui.light(v);}
function scenario(v){dirty=true;renderer.shadowMap.needsUpdate=true;cut=v==='cut';arch.upper.visible=!cut;arch.boats.visible=!cut;furn.upper.visible=!cut;decor.visible=!cut;aux.host.visible=!cut;ui.status(cut?'Corte de leitura · pavimento superior oculto · não é cenário construído':'Projeto REV05 · cotas documentadas + geometria estimada');}
const save=(blob,name)=>{const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);};
async function capture(){ui.toast('Preparando PNG em alta resolução…');const w=innerWidth,h=innerHeight,ratio=renderer.getPixelRatio();try{const width=2560,height=Math.round(width*h/w);renderer.setPixelRatio(1);renderer.setSize(width,height,false);renderer.render(scene,camera);const blob=await new Promise(r=>canvas.toBlob(r,'image/png'));if(!blob)throw Error('Captura indisponível');save(blob,'azimut-spbs-2560.png');ui.toast(`PNG salvo · ${width} × ${height} px`);}catch(e){ui.toast('Falha na captura: '+e.message);}finally{renderer.setPixelRatio(ratio);renderer.setSize(w,h,false);renderer.render(scene,camera);}}
async function exportGLB(){const btns=['export-button','export-mobile'].map(id=>document.getElementById(id));btns.forEach(b=>b.disabled=true);ui.toast('Exportando geometria visível…');try{const out=await new GLTFExporter().parseAsync(model,{binary:true,onlyVisible:true,maxTextureSize:512});save(new Blob([out],{type:'model/gltf-binary'}),'azimut-spbs-visivel.glb');ui.toast('GLB exportado em metros · somente grupos visíveis');}catch(e){console.error(e);ui.toast('Falha na exportação: '+e.message);}finally{btns.forEach(b=>b.disabled=false);}}
ui=interfaceUI({view,home,mode,light,scenario,capture,exportGLB,asset:v=>{dirty=true;renderer.shadowMap.needsUpdate=true;aux.set(v);ui.toast(v==='none'?'Ativo auxiliar removido; arquitetura preservada.':v==='fallback'?'Alternativa procedural ativada.':'GLB original restaurado.');},images:embedded.images});home();light('render');ui.status('Projeto REV05 · cotas documentadas + geometria estimada');
const resize=()=>{dirty=true;if(currentView==='top'&&!walking){camera.fov=2*Math.atan(Math.max(29,36/(innerWidth/innerHeight))/360)*180/Math.PI;}if(currentView==='overall'&&!walking){const f=Math.max(1,1.12/(innerWidth/innerHeight));camera.position.set(15-39*f,1.3+25.7*f,11+31*f);orbit.target.set(15,1.3,11);orbit.update();}camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight,false);};addEventListener('resize',resize);resize();
const handled=['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'];addEventListener('keydown',e=>{if(e.key==='Escape'&&walking){mode();return;}if(!walking||document.querySelector('dialog[open]')||/INPUT|SELECT|TEXTAREA|BUTTON/.test(e.target.tagName))return;if(handled.includes(e.code)){e.preventDefault();keys.add(e.code);}});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>keys.clear());document.addEventListener('visibilitychange',()=>keys.clear());
let drag=null;canvas.addEventListener('pointerdown',e=>{if(walking){drag={x:e.clientX,y:e.clientY,id:e.pointerId};canvas.setPointerCapture(e.pointerId);}});canvas.addEventListener('pointermove',e=>{if(!drag||!walking)return;dirty=true;yaw-=(e.clientX-drag.x)*.004;pitch=T.MathUtils.clamp(pitch-(e.clientY-drag.y)*.004,-1.3,1.3);drag.x=e.clientX;drag.y=e.clientY;});const release=()=>{drag=null;};canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);
for(const b of document.querySelectorAll('[data-key]')){b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.key);});for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>keys.delete(b.dataset.key));}
const clock=new T.Clock();renderer.setAnimationLoop(()=>{const dt=Math.min(clock.getDelta(),.05);if(walking){if(keys.size)dirty=true;if(!document.querySelector('dialog[open]')){let f=Number(keys.has('KeyW')||keys.has('ArrowUp'))-Number(keys.has('KeyS')||keys.has('ArrowDown')),r=Number(keys.has('KeyD')||keys.has('ArrowRight'))-Number(keys.has('KeyA')||keys.has('ArrowLeft'));const len=Math.hypot(f,r)||1;f=f/len*dt*2.8;r=r/len*dt*2.8;feet=move(feet,-Math.sin(yaw)*f+Math.cos(yaw)*r,-Math.cos(yaw)*f-Math.sin(yaw)*r);}camera.position.set(feet[0],feet[1]+L.eye,feet[2]);camera.rotation.set(pitch,yaw,0);}else orbit.update();if(dirty){renderer.render(scene,camera);dirty=false;}});
// Somente diagnóstico de leitura para validação; sem eval, shell ou mutação arquitetônica.
window.__AZIMUT__={snapshot:()=>({ready:true,walking,camera:camera.position.toArray(),feet:[...feet],view:currentView,cut,assetLoaded:aux.loaded,assetChildren:aux.host.children.length,drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,visibleModelChildren:model.children.filter(x=>x.visible).length})};document.body.dataset.ready='true';if(new URLSearchParams(location.search).get('vista')==='materiais'){document.getElementById('view').value='materials';view('materials');}if(new URLSearchParams(location.search).get('vista')==='planta'){document.getElementById('view').value='top';view('top');}
}
start().catch(e=>{console.error(e);const p=document.createElement('p');p.className='fatal';p.textContent='Não foi possível iniciar o visualizador 3D. Verifique se WebGL está habilitado no navegador. '+e.message;document.body.append(p);});
